// Lista completa de bancos brasileiros com dados reais
// Incluindo logos em base64 (ícones simplificados) e cores oficiais

export interface BrazilianBank {
  code: string;
  name: string;
  fullName: string;
  logo: string; // Base64 SVG icon or emoji
  primaryColor: string;
  secondaryColor: string;
  textColor?: string; // Cor do texto para contraste
  ispb: string; // Identificador do Sistema de Pagamentos Brasileiro
  category: 'digital' | 'traditional' | 'fintech';
  openFinanceEnabled: boolean;
  pluggyConnectorId?: string; // ID do conector no Pluggy
  description?: string; // Descrição curta do banco
}

export const BRAZILIAN_BANKS: BrazilianBank[] = [
  {
    code: 'nubank',
    name: 'Nubank',
    fullName: 'Nu Pagamentos S.A.',
    logo: '💜',
    primaryColor: '#8A05BE',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    ispb: '18236120',
    category: 'digital',
    openFinanceEnabled: true,
    description: 'Banco digital com cartão roxinho',
  },
  {
    code: 'itau',
    name: 'Itaú',
    fullName: 'Itaú Unibanco S.A.',
    logo: '🔶',
    primaryColor: '#EC7000',
    secondaryColor: '#003C78',
    textColor: '#FFFFFF',
    ispb: '60701190',
    category: 'traditional',
    openFinanceEnabled: true,
    description: 'Maior banco privado do Brasil',
  },
  {
    code: 'bradesco',
    name: 'Bradesco',
    fullName: 'Banco Bradesco S.A.',
    logo: '🔴',
    primaryColor: '#CC092F',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    ispb: '60746948',
    category: 'traditional',
    openFinanceEnabled: true,
    description: 'Um dos maiores bancos do país',
  },
  {
    code: 'santander',
    name: 'Santander',
    fullName: 'Banco Santander Brasil S.A.',
    logo: '🔴',
    primaryColor: '#EC0000',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    ispb: '90400888',
    category: 'traditional',
    openFinanceEnabled: true,
    description: 'Banco internacional com presença global',
  },
  {
    code: 'caixa',
    name: 'Caixa',
    fullName: 'Caixa Econômica Federal',
    logo: '🔵',
    primaryColor: '#0057A0',
    secondaryColor: '#F37021',
    textColor: '#FFFFFF',
    ispb: '00360305',
    category: 'traditional',
    openFinanceEnabled: true,
    description: 'Banco público federal',
  },
  {
    code: 'bb',
    name: 'Banco do Brasil',
    fullName: 'Banco do Brasil S.A.',
    logo: '💛',
    primaryColor: '#FFD502',
    secondaryColor: '#005CA9',
    textColor: '#005CA9',
    ispb: '00000000',
    category: 'traditional',
    openFinanceEnabled: true,
    description: 'Maior banco estatal brasileiro',
  },
  {
    code: 'inter',
    name: 'Inter',
    fullName: 'Banco Inter S.A.',
    logo: '🧡',
    primaryColor: '#FF7A00',
    secondaryColor: '#000000',
    textColor: '#FFFFFF',
    ispb: '00416968',
    category: 'digital',
    openFinanceEnabled: true,
    description: 'Banco digital completo e gratuito',
  },
  {
    code: 'c6',
    name: 'C6 Bank',
    fullName: 'Banco C6 S.A.',
    logo: '⚫',
    primaryColor: '#000000',
    secondaryColor: '#FFED00',
    textColor: '#FFFFFF',
    ispb: '31872495',
    category: 'digital',
    openFinanceEnabled: true,
    description: 'Banco digital do Grupo BTG Pactual',
  },
  {
    code: 'neon',
    name: 'Neon',
    fullName: 'Neon Pagamentos S.A.',
    logo: '💙',
    primaryColor: '#00D9D9',
    secondaryColor: '#0066FF',
    textColor: '#FFFFFF',
    ispb: '20855875',
    category: 'digital',
    openFinanceEnabled: true,
    description: 'Conta digital sem tarifas',
  },
  {
    code: 'next',
    name: 'Next',
    fullName: 'Banco Next S.A.',
    logo: '💚',
    primaryColor: '#00D86A',
    secondaryColor: '#000000',
    textColor: '#FFFFFF',
    ispb: '00416968',
    category: 'digital',
    openFinanceEnabled: true,
    description: 'Banco digital do Bradesco',
  },
  {
    code: 'original',
    name: 'Original',
    fullName: 'Banco Original S.A.',
    logo: '💚',
    primaryColor: '#4CBF17',
    secondaryColor: '#000000',
    textColor: '#FFFFFF',
    ispb: '92894922',
    category: 'digital',
    openFinanceEnabled: true,
    description: 'Banco digital com cashback',
  },
  {
    code: 'picpay',
    name: 'PicPay',
    fullName: 'PicPay Bank - Banco Múltiplo S.A.',
    logo: '💚',
    primaryColor: '#11C76F',
    secondaryColor: '#000000',
    textColor: '#FFFFFF',
    ispb: '22896431',
    category: 'digital',
    openFinanceEnabled: true,
    description: 'Carteira digital e banco',
  },
  {
    code: 'mercadopago',
    name: 'Mercado Pago',
    fullName: 'Mercado Pago',
    logo: '💙',
    primaryColor: '#00AAFF',
    secondaryColor: '#FFC400',
    textColor: '#FFFFFF',
    ispb: '10573521',
    category: 'fintech',
    openFinanceEnabled: true,
    description: 'Carteira digital do Mercado Livre',
  },
  {
    code: 'will',
    name: 'Will Bank',
    fullName: 'Will Financeira S.A.',
    logo: '💜',
    primaryColor: '#7B1FA2',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    ispb: '00000000',
    category: 'digital',
    openFinanceEnabled: false,
    description: 'Banco digital com investimentos',
  },
  {
    code: 'btg',
    name: 'BTG Pactual',
    fullName: 'BTG Pactual S.A.',
    logo: '🔵',
    primaryColor: '#0033A0',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    ispb: '30306294',
    category: 'traditional',
    openFinanceEnabled: true,
    description: 'Maior banco de investimentos da América Latina',
  },
  {
    code: 'safra',
    name: 'Safra',
    fullName: 'Banco Safra S.A.',
    logo: '🔵',
    primaryColor: '#003366',
    secondaryColor: '#CCCCCC',
    textColor: '#FFFFFF',
    ispb: '58160789',
    category: 'traditional',
    openFinanceEnabled: true,
    description: 'Banco privado brasileiro',
  },
  {
    code: 'pan',
    name: 'Pan',
    fullName: 'Banco Pan S.A.',
    logo: '🔵',
    primaryColor: '#00539C',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    ispb: '59285411',
    category: 'traditional',
    openFinanceEnabled: true,
    description: 'Banco focado em crédito',
  },
  {
    code: 'stone',
    name: 'Stone',
    fullName: 'Stone Pagamentos S.A.',
    logo: '💚',
    primaryColor: '#00D959',
    secondaryColor: '#000000',
    textColor: '#FFFFFF',
    ispb: '16501555',
    category: 'fintech',
    openFinanceEnabled: false,
    description: 'Fintech de pagamentos',
  },
  {
    code: 'bs2',
    name: 'BS2',
    fullName: 'BS2 S.A.',
    logo: '💙',
    primaryColor: '#0066CC',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    ispb: '71027866',
    category: 'digital',
    openFinanceEnabled: true,
    description: 'Banco digital para empresas',
  },
  {
    code: 'agibank',
    name: 'Agibank',
    fullName: 'Agibank S.A.',
    logo: '🔵',
    primaryColor: '#0055AA',
    secondaryColor: '#FFFFFF',
    textColor: '#FFFFFF',
    ispb: '10664513',
    category: 'digital',
    openFinanceEnabled: true,
    description: 'Banco digital com foco em crédito',
  },
];

export function getBankByCode(code: string): BrazilianBank | undefined {
  return BRAZILIAN_BANKS.find((bank) => bank.code === code);
}

export function getBanksByCategory(category: BrazilianBank['category']): BrazilianBank[] {
  return BRAZILIAN_BANKS.filter((bank) => bank.category === category);
}

export function getOpenFinanceEnabledBanks(): BrazilianBank[] {
  return BRAZILIAN_BANKS.filter((bank) => bank.openFinanceEnabled);
}
